include full android env vars in environment.conf for pinentry
There was a backtrace coming from when pinentry-android tries to open the
PinEntryActivity with /system/bin/am, this made that go away.

refs #2744

backtrace:

pinentry-android.c  D  sending intent with: exec /system/bin/am start -n info.guardianproject.gpg/info.guardianproject.gpg.pinentry.PinEntryActivity --activity-no-history --activity-clear-top --ei uid 10043 --user 0
pinentry-android.c  D  start_server /data/data/info.guardianproject.gpg/app_home/S.pinentry
    AndroidRuntime  D  >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
    AndroidRuntime  D  CheckJNI is OFF
          dalvikvm  D  Trying to load lib libjavacore.so 0x0
          dalvikvm  D  Added shared lib libjavacore.so 0x0
          dalvikvm  D  Trying to load lib libnativehelper.so 0x0
          dalvikvm  D  Added shared lib libnativehelper.so 0x0
       Environment  W  EXTERNAL_STORAGE undefined; falling back to default
          dalvikvm  W  Exception Ljava/lang/NullPointerException; thrown while initializing Landroid/os/Debug;
          dalvikvm  I  Exception thrown by dispatcher for 0x48454c4f
          dalvikvm  I  java.lang.ExceptionInInitializerError:
          dalvikvm  I  at android.ddm.DdmHandleHello.handleHELO(DdmHandleHello.java:140)
          dalvikvm  I  at android.ddm.DdmHandleHello.handleChunk(DdmHandleHello.java:86)
          dalvikvm  I  at org.apache.harmony.dalvik.ddmc.DdmServer.dispatch(DdmServer.java:171)
          dalvikvm  I  at dalvik.system.NativeStart.run(Native Method)
          dalvikvm  I  Caused by:
          dalvikvm  I  java.lang.NullPointerException:
          dalvikvm  I  at java.io.File.fixSlashes(File.java:185)
          dalvikvm  I  at java.io.File.<init>(File.java:134)
          dalvikvm  I  at android.os.Environment.getLegacyExternalStorageDirectory(Environment.java:322)
          dalvikvm  I  at android.os.Debug.<clinit>(Debug.java:97)
          dalvikvm  I  at android.ddm.DdmHandleHello.handleHELO(DdmHandleHello.java:140)
          dalvikvm  I  at android.ddm.DdmHandleHello.handleChunk(DdmHandleHello.java:86)
          dalvikvm  I  at org.apache.harmony.dalvik.ddmc.DdmServer.dispatch(DdmServer.java:171)
          dalvikvm  I  at dalvik.system.NativeStart.run(Native Method)
          dalvikvm  I  Rejecting re-init on previously-failed class Landroid/os/Debug; v=0x0
          dalvikvm  I  Exception thrown by dispatcher for 0x46454154
          dalvikvm  I  java.lang.NoClassDefFoundError: android/os/Debug
          dalvikvm  I  at android.ddm.DdmHandleHello.handleFEAT(DdmHandleHello.java:152)
          dalvikvm  I  at android.ddm.DdmHandleHello.handleChunk(DdmHandleHello.java:88)
          dalvikvm  I  at org.apache.harmony.dalvik.ddmc.DdmServer.dispatch(DdmServer.java:171)
          dalvikvm  I  at dalvik.system.NativeStart.run(Native Method)
          dalvikvm  I  Rejecting re-init on previously-failed class Landroid/os/Debug; v=0x0
          dalvikvm  I  Exception thrown by dispatcher for 0x4d505251
          dalvikvm  I  java.lang.NoClassDefFoundError: android/os/Debug
          dalvikvm  I  at android.ddm.DdmHandleProfiling.handleMPRQ(DdmHandleProfiling.java:181)
          dalvikvm  I  at android.ddm.DdmHandleProfiling.handleChunk(DdmHandleProfiling.java:84)
          dalvikvm  I  at org.apache.harmony.dalvik.ddmc.DdmServer.dispatch(DdmServer.java:171)
          dalvikvm  I  at dalvik.system.NativeStart.run(Native Method)